### ISSUE TITLE
where to find the "sequence.gbc.xml" file?

### ISSUE THREAD

**Issue by liamxg** [TheSatoLab/Merbecovirus_recombination#1]
Dear @TheSatoLab,

Could I know where to find the "sequence.gbc.xml" file, thanks.

**Comment by satoxlab** [comment]
Hi @liamxg , I am afraid that you are mentioning the wrong person. Who you should contact is not @satolab.

**Comment by satoxlab** [comment]
@liamxg No problem. Hope @TheSatoLab will respond you soon.

**Comment by JetVirology22** [comment]
Hello @liamxg,
Thank you for the message.
To find **sequence.gbc.xml**, just go to the NCBI website.
First, go to this website: https://www.ncbi.nlm.nih.gov/.
Second, type any accession number/s you need, example: https://www.ncbi.nlm.nih.gov/nuccore/NC_019843.3.
Third, on the upper right corner, there is a **Send to** button and click it, and it should give you a list.
Fourth, under the **Choose Destination**, click File, then under **Format**, click **INSDSeq XML**, and last, click **Create File**.
Finally, the sequence.gbc.xml will be downloaded to your local computer.

Hope this helps!
