### ISSUE TITLE
could I know how to get the `system.file("{recombination-free}.nwk", package = "treeio")` and `system.file("{RBD}.nwk", package = "treeio")` file?

### ISSUE THREAD

**Issue by liamxg** [TheSatoLab/Merbecovirus_recombination#2]
Dear @JetVirology22,

Your project is great, I like it, could you please tell me how to get the `system.file("{recombination-free}.nwk", package = "treeio")` and `system.file("{RBD}.nwk", package = "treeio")` file? thanks.

**Comment by JetVirology22** [comment]
Hello @liamxg,

Thank you for the message.
Regarding the `nwk` files, you have to do first the phylogenetic analysis, then convert your tree file into newick format. 
In this particular script, you can use any tree format like nexus, etc. 
After getting the tree file, you can perform that particular script, then read the tree and so on.
I used R in this analysis. 

Hope this helps!

Jarel
