### ISSUE TITLE
where to find `Strain.name`?

### ISSUE THREAD

**Issue by liamxg** [TheSatoLab/Merbecovirus_recombination#4]
Dear @JetVirology22,

I can not find the column as `Strain.name` when I run `phylogenetic_tree_visualization.R`, is there anything I missed?

Thanks.

**Comment by JetVirology22** [comment]
Hello @liamxg,
The `Strain.name` is a new column created to cluster the viruses according to their groupings. This column is used to matched the color of the groupings.
Example, all MERS-CoV is color: `#02686B`, then NeoCoV is color: '#0433FF', etc.
I created a new metadata file for this grouping for easy visualization. I extracted this new metadata file from `metadata/metadata_Merbeco.csv`. 
Hope this helps!

Jarel
