### ISSUE TITLE
The type of receptor usage of these coronaviruses are determined by sequence or experimental?

### ISSUE THREAD

**Issue by liamxg** [TheSatoLab/Merbecovirus_recombination#5]
Dear @JetVirology22,

Could I know the type of receptor usage of these coronaviruses are determined by sequence or experimental?

**Comment by JetVirology22** [comment]
Hello @liamxg ,
They are all based from experimental. So we searched for papers for each of these sequences.

**Comment by JetVirology22** [comment]
@liamxg ,
Unidentified means they performed experiment but it did not showed any efficient receptor usage. From the tree, the only unidentified is the **Hedgehog-CoV-1** clade.

**Comment by JetVirology22** [comment]
@liamxg ,
yes you are right. Sorry, I forgot about that group.
