### ISSUE TITLE
how to define the breakpoints with CI?

### ISSUE THREAD

**Issue by liamxg** [TheSatoLab/Merbecovirus_recombination#6]
Dear @JetVirology22,

I find that the breakpoints  in Fig. 2A with red color are different from SuppleTable 2, the breakpoints have 99% CI, I am confused, could you please help me out, thanks.

**Comment by JetVirology22** [comment]
@liamxg ,
You are right. The breakpoints were identified in the RDP5, and the imported data is a sequence aligned. Once we get the breakpoints, we patterned it on the original position in the GenBank. See TableS3. 
The CI from these breakpoints were given in the RDP5 result.

**Comment by JetVirology22** [comment]
@liamxg ,
Yes, you are correct!
