### ISSUE TITLE
any code for Fig. 4?

### ISSUE THREAD

**Issue by liamxg** [TheSatoLab/Merbecovirus_recombination#7]
Dear @JetVirology22,

Fig4 has map with host pictures, that's really nice. Could you please upload the code and data, thanks.

**Comment by JetVirology22** [comment]
Hello @liamxg ,

For the code, I just follow this script: https://shinichiro-iwata.github.io/geospatial-data-visualization/rnaturalearth-visualization.html. So I mainly use the rnaturalearth, tidyverse and sf packages.

After getting the world map, I edited it in the Adobe Illustrator.

**Comment by JetVirology22** [comment]
@liamxg ,
The pictures were retrieved from some of our published papers, e.g. https://www.pnas.org/doi/epdf/10.1073/pnas.1914183116. I got the pictures from them and used it in the paper. 

Alternatively, you can use PhyloPic (https://www.phylopic.org/) to get the animal pictures but be cautious on the permission for each silhouette images. Hope this helps!
